version: '3'
services:
    ui:
        build:
            context: ui
        volumes:
           - './ui:/app'
           - '/app/node_modules'
        ports:
          - 3000:3000
        depends_on:
            - api
            - stud-db

    api:
        build:
            context: api
        volumes:
            - "./api:/app/api"
        environment:
          - CHOKIDAR_USEPOLLING=true
          - PORT=5050 
          - DEBUG=True
        ports:
          - 5050:5050

    stud-db:
        image: mongo
        volumes:
            - db:/data/db
            # after creating db volume
            # - "./dump:/dump"
        ports:
            - 27017:27017

volumes:
    db:
