FROM nginx
ARG API=studentischerfilmclub.com/api
WORKDIR /usr/share/nginx/html

COPY . .
RUN chmod -R o+r .
RUN chmod o+x assets

RUN sed -i 's%API_URL = .*%API_URL = "https://studentischerfilmclub.holten.com/api/"%' api.js
RUN sed -i 's%API_WS_URL = .*%API_WS_URL = "wss://studentischerfilmclub.holten.com/api/"%' api.js
