FROM python:3.11
WORKDIR /app

ENV DEBUG=false

COPY ./requirements.txt ./requirements.txt
RUN  pip install --no-cache-dir --upgrade -r ./requirements.txt
COPY . ./api

EXPOSE 80
CMD uvicorn api.main:app \
    --host "0.0.0.0"       \
    --port "80"            \
    --log-level info  \
    --proxy-headers 
