ARG HOST=0.0.0.0
ARG PORT=80

FROM python:3.11
WORKDIR /app

ENV DEBUG=false

COPY ./requirements.txt ./requirements.txt
RUN  pip install --no-cache-dir --upgrade -r ./requirements.txt
COPY . ./api

CMD uvicorn api.main:app \
    --host "$HOST"       \
    --port "$PORT"       \
    --workers 4          \
    --log-level warning  \
    --proxy-headers      \